platform :ios, '12.0'

target 'FBExampleObjc' do
  use_frameworks!

  # FB_USE_LOCAL=1 pod install → use the local xcframework; otherwise the remote spec is used.
  if ENV['FB_USE_LOCAL'] == '1'
    pod 'Facebetter', :path => '../../build/ios'
  else
    pod 'Facebetter', '1.4.5'
  end
end
